name: Release UM Admin

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release UM Admin
    runs-on: ubuntu-latest
    environment:
      name: UM_PROD
    env:
      VITE_MAIL_PROXY_URL: ${{ vars.MAIL_PROXY_URL }}
      VITE_MAIL_PROXY_API_KEY: ${{secrets.MAIL_PROXY_API_KEY}}
      VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Install modules
        run: npm install

      - name: Ingest package version
        uses: nyaa8/package-version@v1

      - name: Build app
        run: npm run build

      - name: Remove index.html
        run: rm build/index.html

      - name: Clean remote folder
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          remoteFiles: 'main.*.js;'
          remoteDirectories: ${{ vars.REMOTE_DIR }}
          ignoreSSL: '1'

      - name: Upload app
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          protocol: ftp
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ${{ github.workspace }}/build
          server-dir: ${{ vars.REMOTE_DIR }}
