name: Version Increment

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v11.0.7'
        with:
          patch-wording: 'fix,deps'
          minor-wording: 'new,feat,minor'
          major-wording: 'major'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
